# Makefile — the front door. Run `make` (or `make help`) to see everything.
#
# Defaults match a wafer.space gf180mcuD shuttle, slot 1x1. Override on the
# command line, e.g.  `make harden SLOT=1x0p5`.
MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

TOP = chip_top

# ---- PDK selection (gf180mcuD via ciel, pinned commit) ----------------------
# PDK_ROOT is the host folder bind-mounted to /pdk inside the containers
# (docker-compose uses ./pdk by default); it doubles as the local PDK dir for
# Path B / native use.
PDK_ROOT ?= $(MAKEFILE_DIR)/pdk
PDK ?= gf180mcuD
PDK_COMMIT ?= 019cf7a3e0de79bb0e4b6213758882d283c65816

# ---- Standard-cell library (SCL) --------------------------------------------
# Available: gf180mcu_fd_sc_mcu7t5v0 (default), gf180mcu_fd_sc_mcu9t5v0,
#            gf180mcu_as_sc_mcu7t3v3
SCL ?= gf180mcu_fd_sc_mcu7t5v0

# ---- I/O pad library --------------------------------------------------------
# Available: gf180mcu_fd_io (default), gf180mcu_ocd_io
PAD ?= gf180mcu_fd_io

# ---- SRAM macro library (only matters if your design uses SRAM) -------------
SRAM ?= gf180mcu_fd_ip_sram
ifeq ($(SRAM),gf180mcu_fd_ip_sram)
    MACROS = 5v
else
    MACROS = 3v3
endif

# ---- Slot (physical area on the shuttle reticle) ----------------------------
AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5
DEFAULT_SLOT = 1x1
SLOT ?= $(DEFAULT_SLOT)
ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
    $(error $(SLOT) is not one of AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

# Defines fed into the RTL so it knows which slot/SRAM it is being built for.
SLOT_DEFINE = SLOT_$(shell echo $(SLOT) | tr '[:lower:]' '[:upper:]')
SRAM_DEFINE = SRAM_$(SRAM)

# ---- The LibreLane command line (IDENTICAL for Path A and Path B) -----------
# PDK_ROOT here is the IN-CONTAINER path. --manual-pdk = use the PDK we fetched
# ourselves (do not let LibreLane download it).
LIBRELANE_PDK_ROOT ?= /pdk
LIBRELANE_OPTS = --pdk $(PDK) --pdk-root $(LIBRELANE_PDK_ROOT) --manual-pdk --scl $(SCL) --pad $(PAD)
LIBRELANE_CONFIGS = librelane/slots/slot_$(SLOT).yaml librelane/macros/macros_$(MACROS).yaml librelane/config.yaml
LIBRELANE_CMD = SRAM_DEFINE=$(SRAM_DEFINE) librelane $(LIBRELANE_CONFIGS) $(LIBRELANE_OPTS) --save-views-to /work/final

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target] [SLOT=1x1 ...]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-18s %s\n", $$1, $$2}'
.PHONY: help

build-sim: ## Build the simulation Docker image (do this once)
	docker compose build sim
.PHONY: build-sim

build-harden: ## Build the hardening Docker image (do this once)
	docker compose build harden
.PHONY: build-harden

defines: ## Generate src/generated_defines.svh from the current SLOT/SRAM
	@echo "Writing src/generated_defines.svh (SLOT=$(SLOT) SRAM=$(SRAM))"
	@printf '// AUTO-GENERATED by the Makefile. Do not edit; do not commit.\n' > src/generated_defines.svh
	@printf '`define %s\n' '$(SLOT_DEFINE)' >> src/generated_defines.svh
	@printf '`define %s\n' '$(SRAM_DEFINE)' >> src/generated_defines.svh
.PHONY: defines

pdk: build-harden ## Download the gf180mcuD PDK into ./pdk (one-time, ~4 GB)
	docker compose run --rm harden \
	    ciel enable $(PDK_COMMIT) --pdk-root /pdk --pdk-family $(PDK) --include-libraries all
.PHONY: pdk

sim: build-sim defines ## Run the fast no-PDK self-checking test (Icarus) -- the green check
	docker compose run --rm sim \
	    bash -lc 'iverilog -g2012 -Wall -o /tmp/core.vvp src/chip_core.sv tb/tb_chip_core.sv && vvp /tmp/core.vvp'
.PHONY: sim

test: sim ## Alias for `sim` (green here = the scaffold pipeline works end to end)
.PHONY: test

sim-cocotb: build-sim defines pdk ## OPTIONAL: PDK-aware cocotb sim of the full chip_top (needs the PDK)
	docker compose run --rm sim \
	    bash -lc 'cd cocotb && PDK_ROOT=/pdk PDK=$(PDK) SLOT=$(SLOT) PAD=$(PAD) SCL=$(SCL) SRAM=$(SRAM) python3 chip_top_tb.py'
.PHONY: sim-cocotb

harden: build-harden pdk defines ## PATH A (default): harden RTL -> GDSII via the LibreLane Docker image
	docker compose run --rm harden bash -lc '$(LIBRELANE_CMD)'
.PHONY: harden

harden-nix: defines ## PATH B (advanced): harden inside the Nix devshell (`nix develop` first)
	@echo "Run this from inside a Nix devshell (`nix develop`), with the PDK fetched."
	$(LIBRELANE_CMD:--pdk-root /pdk=--pdk-root $(PDK_ROOT))
.PHONY: harden-nix

open-klayout: build-harden ## Open the most recent hardening run in KLayout (Path A)
	docker compose run --rm harden bash -lc \
	    'SRAM_DEFINE=$(SRAM_DEFINE) librelane $(LIBRELANE_CONFIGS) $(LIBRELANE_OPTS) --last-run --flow OpenInKLayout'
.PHONY: open-klayout

open-openroad: build-harden ## Open the most recent hardening run in OpenROAD (Path A)
	docker compose run --rm harden bash -lc \
	    'SRAM_DEFINE=$(SRAM_DEFINE) librelane $(LIBRELANE_CONFIGS) $(LIBRELANE_OPTS) --last-run --flow OpenInOpenROAD'
.PHONY: open-openroad

clean: ## Remove generated sim/harden artifacts (keeps the PDK in ./pdk)
	rm -rf cocotb/sim_build cocotb/results.xml cocotb/__pycache__ \
	       librelane/runs final src/generated_defines.svh
.PHONY: clean
