#!/usr/bin/env bash
# scripts/gen_defines.sh — write src/generated_defines.svh from SLOT/SRAM.
# This file is auto-generated and git-ignored; the RTL `include`s it to learn
# which slot/SRAM it is being built for.
set -euo pipefail

SLOT=${SLOT:-1x1}
SRAM=${SRAM:-gf180mcu_fd_ip_sram}

# SLOT_1X0P5, SLOT_1X1, ... (uppercased, matches the slot YAMLs' VERILOG_DEFINES)
SLOT_DEFINE="SLOT_$(printf '%s' "${SLOT}" | tr '[:lower:]' '[:upper:]')"
SRAM_DEFINE="SRAM_${SRAM}"

OUT="$(git rev-parse --show-toplevel)/src/generated_defines.svh"
{
    printf '// AUTO-GENERATED by gen_defines.sh / make defines. Do not edit; do not commit.\n'
    printf '`define %s\n' "${SLOT_DEFINE}"
    printf '`define %s\n' "${SRAM_DEFINE}"
} > "${OUT}"
echo "Wrote ${OUT}  (${SLOT_DEFINE}, ${SRAM_DEFINE})"
